version: '2'
services:
    edasclientapplication-app:
        image: edasclientapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://edasclientapplication-mysql:3306/edasclientapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    edasclientapplication-mysql:
        extends:
            file: mysql.yml
            service: edasclientapplication-mysql
